# Generated by Django 4.0.2 on 2022-03-22 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_delete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_protect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='comment_protect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=30)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo_delete.post')),
            ],
        ),
    ]
