# Generated by Django 3.2.5 on 2022-03-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(default=None, upload_to='image')),
                ('desc', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.items')),
                ('author', models.CharField(max_length=50)),
                ('publishingCompany', models.CharField(max_length=50)),
            ],
            bases=('home.items',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.items')),
                ('size', models.CharField(max_length=3)),
                ('material', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
            bases=('home.items',),
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.items')),
                ('insurance', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
            bases=('home.items',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.items')),
                ('hardware', models.CharField(max_length=50)),
                ('insurance', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
            bases=('home.items',),
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.items')),
                ('insurance', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
            bases=('home.items',),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.items')),
                ('size', models.CharField(max_length=3)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
            bases=('home.items',),
        ),
    ]
