# Generated by Django 3.2.5 on 2022-03-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
